# Generated by Django 4.2.16 on 2024-12-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_transacoes', '0003_alter_transacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacao',
                                    to='gestor_transacoes.cliente', to_field='cpf', verbose_name='Cliente (CPF)'),
        ),
    ]
